### ISSUE TITLE
Draft docs for jacoco support

### ISSUE THREAD

**Issue by manishas** [Shippable/docsv2#588]
https://github.com/Shippable/pm/issues/7036

Please provide a draft of how Jacoco code coverage support works so we can include it in the docs.

**Comment by ankunath** [comment]
Jacoco is used for code coverage analysis in Java VM based environments. It be used for the java projects by using the Maven plug-in, which provides the report creation in jacoco format.
The project should have a pom.xml file, which includes the maven plugin for jacoco.

The file structure of the basic java project should look like this
![image](https://cloud.githubusercontent.com/assets/8400545/21044212/cd94babc-be20-11e6-8653-a53212a6d4a0.png)

In shippable.yml

```
language: java

jdk:
  - oraclejdk7

build:
  # set the advanceReporting tag to true.
  advancedReporting: true
  ci:
    # create codecoverage folder similar to the testresults for the coverage
    - mkdir -p shippable/codecoverage

    # mvn install will create a `target` folder which will contain a jacoco.xml
    # jacoco.xml will be present at path `target/site/jacoco/`
    - mvn install

    # copy this target folder to the `shippable/codecoverage` folder
    - cp -r target shippable/codecoverage

```  
![image](https://cloud.githubusercontent.com/assets/8400545/21044201/bdd54894-be20-11e6-85b6-f5c19c93d411.png)

and if advanceReporting: true is missing 
![image](https://cloud.githubusercontent.com/assets/8400545/21044643/05f0fd88-be23-11e6-979a-6d9df66dc2ee.png)

**Comment by trriplejay** [comment]
can we also include screenshots of the different levels? for example,  in your advancedReporting screenshot, you could click on `com/myCompany/app` and it change the display to show that package, then you could click on a method and the display would change again to show details about that specific method, etc.  Just so that it's clear that there is a lot of detail on the page. Otherwise, the user may never try to click the left cloumn and would never know that they can view more details.

**Comment by ankunath** [comment]
@trriplejay , yeah sure, I will also add the sample projects and update the docs to add support for `ant` and `gradle` build tool, as discussed.

**Comment by ankunath** [comment]
Gradle support for generating code coverage
The project should have a build.gradle file, which is used to generate the jacoco test report.

In shippable.yml

```
language: java

jdk:
  - oraclejdk7

build:
  # set the advanceReporting tag to true.
  advancedReporting: true
  ci:
    # create codecoverage folder similar to the testresults for the coverage
    - mkdir -p shippable/codecoverage

    # it will build the project and generate the test reports
    - gradle clean build
    - gradle jacocoTestReport

    # copy this target folder to the `shippable/codecoverage` folder
    # the target folder can be specified to any path in build.gradle
    - cp -r build/target shippable/codecoverage

```  
if advanceReporting is true
![image](https://cloud.githubusercontent.com/assets/8400545/21131723/34bdaeca-c136-11e6-9794-ba55b465bb88.png)

**Comment by ankunath** [comment]
Ant support for generating code coverage
The project should have a build.xml file, which is used to generate the jacoco coverage report.

In shippable.yml

```
language: java

jdk:
  - oraclejdk7

build:
  # set the advanceReporting tag to true.
  advancedReporting: true
  ci:
    # create codecoverage folder similar to the testresults for the coverage
    - mkdir -p shippable/codecoverage

    # it will generate the coverage reports
    - ant

    # copy this target folder to the `shippable/codecoverage` folder
    # the target folder can be specified to any path in build.xml
    - cp -r target shippable/codecoverage

```  
if advanceReporting is true

![image](https://cloud.githubusercontent.com/assets/8400545/21132630/0637abdc-c13b-11e6-948a-5a55b2e05283.png)

link for the sample project https://github.com/ankunath/sample_ant_jacoco
