### ISSUE TITLE
Jenkins integration docs

### ISSUE THREAD

**Issue by manishas** [Shippable/docsv2#589]
https://github.com/Shippable/pm/issues/7036

Please provide a draft with screenshots on how Jenkins integration works so we can include it in docs.

**Comment by ankunath** [comment]
Jenkins job shows the status of a job in the jenkins. User can run a specific project in jenkins and use our shippable pipelines to watch the status of that job.

For the jenkins integration, the user has to provide the 
1. Url of the jenkins dashboard.
2. User name for jenkins.
3. Password for jenkins.

And to use shippable pipelines to view the job status, user can add a job resource in shippable.jobs.yml
User has to add the below yml in the shippable.jobs.yml

```
- name: foo-app-ci # Any user made name
    type: jenkinsJob # The type of the job (should not be changed by the user)
    integration: "jenkins"  # Any user made jenkins integration name
    pointer:
      sourceName: "firstjob" # Jenkins job name

```
the status of the jenkins job from shippable pipelines
![image](https://cloud.githubusercontent.com/assets/8400545/21177154/d743a1fc-c20f-11e6-8cdd-8e780623e7ee.png)

On clicking the jenkins job, the user will be redirected to the root url of the jenkins server.
![image](https://cloud.githubusercontent.com/assets/8400545/21177944/481c6348-c213-11e6-9480-a5057add2000.png)
